export const synonymMap: Record<string, string[]> = {
  // Greetings
  "hello": ["hi", "hey", "greetings", "good day", "hello there", "howdy"],
  "hi": ["hello", "hey", "greetings", "good day"],
  "hey": ["hi", "hello", "greetings", "yo"],

  // Common verbs
  "get": ["obtain", "receive", "grab", "secure", "access", "acquire"],
  "want": ["need", "desire", "would love", "are looking for", "wish for"],
  "need": ["require", "are looking for", "want", "seek"],
  "use": ["utilize", "make use of", "employ", "apply", "leverage"],
  "see": ["view", "check out", "look at", "discover", "explore"],
  "know": ["be aware", "understand", "realize", "find out"],
  "make": ["create", "build", "develop", "produce", "generate"],
  "take": ["grab", "pick up", "seize", "claim"],
  "find": ["discover", "locate", "uncover", "come across"],
  "show": ["display", "reveal", "present", "demonstrate"],
  "keep": ["maintain", "hold", "preserve", "retain"],
  "give": ["offer", "provide", "deliver", "send"],
  "start": ["begin", "kick off", "launch", "initiate", "commence"],
  "stop": ["pause", "end", "halt", "cease"],
  "help": ["assist", "support", "guide", "aid"],
  "try": ["attempt", "give it a shot", "test", "explore"],
  "ask": ["inquire", "reach out", "contact", "get in touch"],
  "tell": ["inform", "let know", "share", "notify"],
  "think": ["believe", "feel", "consider", "reckon"],
  "look": ["check", "view", "glance at", "explore"],
  "work": ["function", "operate", "run", "perform"],
  "come": ["visit", "join", "stop by", "drop in"],
  "go": ["head", "move", "proceed", "navigate"],
  "talk": ["chat", "speak", "discuss", "connect"],
  "send": ["forward", "share", "dispatch", "deliver"],
  "share": ["send", "forward", "spread", "pass on"],

  // Time
  "now": ["today", "at this moment", "right away", "immediately", "at once"],
  "today": ["this very day", "right now", "at this time"],
  "soon": ["shortly", "in a moment", "before long", "any time now"],
  "quickly": ["fast", "rapidly", "swiftly", "in no time"],
  "always": ["consistently", "every time", "without fail", "constantly"],

  // Action words
  "check": ["view", "see", "look at", "explore", "discover", "review"],
  "offer": ["deal", "discount", "special", "package", "opportunity", "proposal"],
  "buy": ["purchase", "get", "order", "secure", "grab", "invest in"],
  "join": ["sign up", "register", "become a member", "enter", "enroll"],
  "contact": ["reach out to", "get in touch with", "connect with", "message"],
  "save": ["keep", "preserve", "protect", "store", "retain"],
  "learn": ["discover", "find out", "explore", "understand", "uncover"],
  "improve": ["enhance", "boost", "upgrade", "better", "strengthen"],
  "grow": ["expand", "scale", "develop", "increase", "build"],
  "launch": ["start", "begin", "initiate", "kickoff", "release", "introduce"],

  // Descriptors
  "new": ["latest", "recent", "fresh", "upcoming", "brand-new", "cutting-edge"],
  "best": ["greatest", "top", "premium", "excellent", "superior", "finest"],
  "good": ["great", "excellent", "solid", "strong", "quality"],
  "great": ["amazing", "fantastic", "excellent", "wonderful", "outstanding"],
  "big": ["large", "major", "significant", "substantial", "massive"],
  "small": ["minor", "little", "compact", "modest"],
  "easy": ["simple", "straightforward", "effortless", "hassle-free"],
  "fast": ["quick", "rapid", "speedy", "instant", "swift"],
  "free": ["complimentary", "no-cost", "at no charge", "on us", "gratis"],
  "special": ["exclusive", "unique", "one-of-a-kind", "remarkable"],
  "limited": ["exclusive", "rare", "restricted", "short-term", "scarce"],
  "important": ["critical", "essential", "urgent", "must-see", "vital", "key"],
  "amazing": ["incredible", "fantastic", "remarkable", "outstanding", "impressive"],
  "exclusive": ["special", "limited", "members-only", "private", "select"],
  "real": ["genuine", "authentic", "true", "actual"],
  "simple": ["easy", "straightforward", "effortless", "uncomplicated"],

  // Business/marketing
  "message": ["text", "note", "update", "info", "notification"],
  "please": ["kindly", "if you can", "would you mind", "whenever possible"],
  "thanks": ["thank you", "much appreciated", "cheers", "grateful"],
  "price": ["cost", "value", "amount", "rate", "investment"],
  "business": ["company", "enterprise", "organization", "firm", "venture"],
  "leads": ["prospects", "potential clients", "targets", "contacts"],
  "bulk": ["mass", "large-scale", "group", "volume"],
  "verify": ["check", "validate", "confirm", "authenticate"],
  "product": ["item", "service", "solution", "offering"],
  "service": ["solution", "offering", "support", "assistance"],
  "opportunity": ["chance", "opening", "possibility", "prospect"],
  "deal": ["offer", "package", "arrangement", "agreement"],
  "results": ["outcomes", "achievements", "success", "gains"],
  "information": ["details", "info", "data", "facts"],
  "solution": ["answer", "fix", "resolution", "approach"],
  "team": ["group", "crew", "staff", "people"],
  "clients": ["customers", "partners", "users", "members"],
  "success": ["achievement", "accomplishment", "victory", "win"],
  "goal": ["target", "objective", "aim", "purpose"],
  "strategy": ["plan", "approach", "method", "roadmap"],
}
